### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Vitor-Bukovitz** [NatanMkz/bot_discord#1]
recomendo fazer o repositório privado, pois vc colocou seu token no código, qualquer um que acessar o repositório, vai poder controlar seu bot ;)

**Comment by NatanMkz** [comment]
> recomendo fazer o repositório privado, pois vc colocou seu token no código, qualquer um que acessar o repositório, vai poder controlar seu bot;)

eu vi isso só depois, mas já mudei o token, obrigado ;)
